apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ckim
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ckim-harbor-project/db@sha256:e2359c69ed4929324bcd08ac8e694d0e6cb527f7ec02d9cbb2abb8c5a82c4a9a
        ports:
        - containerPort: 5432
